### ISSUE TITLE
tags returned 404

### ISSUE THREAD

**Issue by velo** [microscaling/imagelayers#29]
Got the following error when I try to evaluate my own image...

```
vendor.js:5 GET https://imagelayers.io/registry/images/velo/shippable-android-buildimage/tags 500 (Internal Server Error)(anonymous function) @ vendor.js:5v @ vendor.js:5j @ vendor.js:4i @ vendor.js:5(anonymous function) @ vendor.js:5$eval @ vendor.js:5$digest @ vendor.js:5(anonymous function) @ vendor.js:5g @ vendor.js:4(anonymous function) @ vendor.js:4
scripts.js:1 Error:  GET https://registry-1.docker.io/v1/repositories/velo/shippable-android-buildimage/tags returned 404
```

But it is there, it's public, not sure why 404
https://hub.docker.com/r/velo/shippable-android-buildimage/

**Comment by rossf7** [comment]
Unfortunately ImageLayers only works with V1 of the Docker Registry API. Your image must have been built with Docker 1.10 or later so it was pushed to the V2 registry.

To see your tags you first call the auth service to get a token and then call the V2 Registry API.

```
curl https://auth.docker.io/token?service=registry.docker.io&scope=repository:h3nrik/nginx-ldap:pull
curl -H 'Authorization Bearer *** token ***' https://registry.hub.docker.com/v2/h3nrik/nginx-ldap/tags/list
```

We're hoping to add V2 support to ImageLayers but we don't have a date for that. Until then you can get a similar badge from [MicroBadger](https://microbadger.com/).
